# Задание на повторение материала

In [1]:
import numpy as np

## Задание 1

Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [2]:
a = np.arange(12, 24, 1)
print(a)

[12 13 14 15 16 17 18 19 20 21 22 23]


## Задание 2

Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [3]:
a_1 = a.reshape(2, 6)
print(a_1)
a_2 = a.reshape(3, 4)
print(a_2)
a_3 = a.reshape(4, 3)
print(a_3)
a_4 = a.reshape(6, 2)
print(a_4)
a_5 = a.reshape(12, 1)
print(a_5)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


## Задание 3

Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [4]:
a_1 = a.reshape(-1, 6)
print(a_1)
a_2 = a.reshape(-1, 4)
print(a_2)
a_3 = a.reshape(4, -1)
print(a_3)
a_4 = a.reshape(6, -1)
print(a_4)
a_5 = a.reshape(12, -1)
print(a_5)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


## Задание 4

Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

Нет. Если извлечь из него первый элемент, то можно увидеть, что он представляет собой массив, а не число, как в одномерном массиве состоящем из одной строки и 12 столбцов:

In [5]:
z = a[0]
print(type(z))

<class 'numpy.int32'>


In [6]:
z = a_5[0]
print(type(z))

<class 'numpy.ndarray'>


## Задание 5

Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [7]:
b = np.random.randn(3, 4)
print(b)
b_1 = b.flatten()
print(b_1)
print(b.size == b_1.size)

[[ 1.59278593 -0.53327277  0.32367387 -0.80378279]
 [ 1.52529926 -0.7155642  -1.74537897  2.69079226]
 [-0.29143141 -0.00483039 -0.26578668  1.26698465]]
[ 1.59278593 -0.53327277  0.32367387 -0.80378279  1.52529926 -0.7155642
 -1.74537897  2.69079226 -0.29143141 -0.00483039 -0.26578668  1.26698465]
True


## Задание 6

Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [8]:
a = np.arange(20, 0, -2)
print(a)

[20 18 16 14 12 10  8  6  4  2]


## Задание 7

Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?


In [9]:
b = np.arange(20, 1, -2).reshape(10, -1)
print(b)

[[20]
 [18]
 [16]
 [14]
 [12]
 [10]
 [ 8]
 [ 6]
 [ 4]
 [ 2]]


Массив b - двумерный, а массив а - одномерный.



## Задание 8

Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.


In [10]:
a =  np.zeros((2, 2))
b =  np.ones((3, 2))
c = np.vstack((a, b))
print(c)
print(c.size == 10)

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
True


## Задание 9

Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?


In [26]:
a = np.arange(0, 12, 1)
A = a.reshape(4, 3)
At = A.T
B = A.dot(At)
print(a)
print(A)
print(At)
print(B)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]


Матрица B имеет размер 4*4, т.е. количество строк и столбцов в ней равно количеству строк в матрице А или столбцов в матрице At .

In [27]:
d = np.linalg.det(B)
print(d)

0.0


Поскольку определитель матрицы В равен 0, вычислить обратную матрицу для нее нельзя.

## Задание 10

Инициализируйте генератор случайных чисел с помощью объекта seed, равного 42.


In [28]:
import random
random.seed(42)
print(random.random())

0.6394267984578837


## Задание 11

Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [29]:
c = np.arange(0, 16, 1)
np.random.shuffle(c)
print(c)

[ 2  0  5  6  1 15  9  7  3  8 13 10 11 14 12  4]


## Задание 12

Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.


In [30]:
C = c.reshape(4, 4)
print(C)

[[ 2  0  5  6]
 [ 1 15  9  7]
 [ 3  8 13 10]
 [11 14 12  4]]


In [31]:
D = B + C * 10
print(D)

[[ 25  14  73  92]
 [ 24 200 176 192]
 [ 53 166 279 312]
 [142 262 332 342]]


In [32]:
d = np.linalg.det(D)
print(d)

-25816800.000000007


In [33]:
r = np.linalg.matrix_rank(D)
print(r)

4


In [34]:
D_inv = np.linalg.inv(D)
print(D_inv)

[[ 0.02678256  0.00208856 -0.019203    0.00914133]
 [ 0.00709306  0.01236327 -0.0102228   0.00047721]
 [-0.10754857 -0.0445028   0.05094047  0.00744322]
 [ 0.08784977  0.0328631  -0.03364631 -0.00846271]]


## Задание 13

Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [36]:
D_1 = D_inv.flatten()
D_2 = []
for i in D_1:
    if float(i) < 0:
        D_2.append(0)
    else:
        D_2.append(1)
for i in D_2:
    if i != 0 and i != 1:
        print('Mistake')
    else:
        'Ok'
D_3 = np.array(D_2)
D_4 = D_3.reshape(4, 4)
print(D_4)

[[1 1 0 1]
 [1 1 0 1]
 [0 0 1 1]
 [1 1 0 0]]


In [37]:
ind_B = np.where(D_4 == 1)
b = B[ind_B]
print(b)

[  5  14  32  14  50 122 149 212  32 122]


In [38]:
ind_C = np.where(D_4 == 0)
c = C[ind_C]
print(c)

[ 5  9  3  8 12  4]


In [39]:
D_4[ind_B] = B[ind_B]
D_4[ind_C] = C[ind_C]
print(D_4)

[[  5  14   5  32]
 [ 14  50   9 122]
 [  3   8 149 212]
 [ 32 122  12   4]]
